### ISSUE TITLE
ResNet-50 weights

### ISSUE THREAD

**Issue by elias-ramzi** [fanconic/this-does-not-look-like-that#5]
Hi,

Thank you for this repo and the weights that have been made available.

Did you train a ProtoPNet with a resnet50 backbone ? If yes do you intend to release the weights ?

Thanks :)

**Comment by fanconic** [comment]
Hi there! Glad that this repo helped you :)

Unfortunately, we did not train a ResNet50. However you should be able to train it by only changing a parameter in the settings.py file.

**Comment by elias-ramzi** [comment]
Hi,

Ok, thank you for your response :)
