### ISSUE TITLE
Pretrained weights

### ISSUE THREAD

**Issue by Treeboy2762** [fanconic/this-does-not-look-like-that#6]
Thank you for posting your work available. The paper was an interesting read, too.

I have noticed that the link for the pretrained weights is no longer available. May I request for an update?

**Comment by fanconic** [comment]
Thank you for making us aware of this, we shall update it to a new link soon!

**Comment by Treeboy2762** [comment]
Can't thank you more! I'll leave it open for now, please close it at your wish.

**Comment by fanconic** [comment]
Thank you @Treeboy2762 for bringing this to our attention. We have now moved the weights to a Google Drive folder and updated the README.  It was merged in Pull Request #8 .

Just as a disclaimer, I have not retested if everything works. Please let me know in case it shouldn't. I will close this issue, but feel free to reopen it, in case something does not work
